<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tabtab.Presentation\Tabtaba.Presentation.csproj" />
    <ProjectReference Include="..\Tabtaba.ServicesAbstraction\Tabtaba.ServicesAbstraction.csproj" />
    <ProjectReference Include="..\Tabtaba.Services\Tabtaba.Services.csproj" />
    <ProjectReference Include="..\Tabtba.Shared\Tabtaba.Shared.csproj" />
    <ProjectReference Include="..\Tbtba.Infrastructure\Tabtaba.Persistence.csproj" />
    <ProjectReference Include="..\tbtba\Tabtaba.Domain.csproj" />
  </ItemGroup>

</Project>
