<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<InvariantGlobalization>true</InvariantGlobalization>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tabtaba.Persistence\Tabtaba.Persistence.csproj" />
		<ProjectReference Include="..\Tabtaba.Services\Tabtaba.Services.csproj" />
	</ItemGroup>

</Project>