<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tabtaba.ServicesAbstraction\Tabtaba.ServicesAbstraction.csproj" />
    <ProjectReference Include="..\tbtba\Tabtaba.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\AuthenticationServices\Commands\" />
    <Folder Include="Features\MappingProfiles\" />
  </ItemGroup>

</Project>
