<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.57.0" />
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Tabtab.Presentation\Tabtaba.Presentation.csproj" />
		<ProjectReference Include="..\Tabtaba.ServicesAbstraction\Tabtaba.ServicesAbstraction.csproj" />
		<ProjectReference Include="..\Tabtba.Shared\Tabtaba.Shared.csproj" />
		<ProjectReference Include="..\Tbtba.Infrastructure\Tabtaba.Persistence.csproj" />
		<ProjectReference Include="..\tbtba\Tabtaba.Domain.csproj" />
	</ItemGroup>
</Project>